name: Bussiness Card Builder

on:
  push:
    branches:
      - source
  repository_dispatch:
    types: [redeploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        uses: SophiaSaiada/business-card-builder-gh-action@master
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Call On-Done Webhook
        uses: joelwmale/webhook-action@6b83612926bbb8cdb65da3c1bedc9c08dea5810b
        env:
          WEBHOOK_URL: ${{ secrets.ON_PUBLISH_DONE_WEBHOOK_URL }}
          data: ${{ github.repository }}
